### ISSUE TITLE
"Unresolved Dependency" issue - please update README.md

### ISSUE THREAD

**Issue by roansong** [OOPMan/span-digital-exercise#2]
Hello sir @OOPMan[.](https://www.reddit.com/r/Ooer/)

I am trying to build from source and run tests, but I when I run ```sbt assembly``` it is failing to find a module: ```module not found: com.artima.supersafe#sbtplugin;1.1.6```. 

To fix this I had to update my ~/.sbt/1.0/global.sbt file with this line as per the [ScalaTest docs](http://www.scalatest.org/supersafe#installation): 

```
resolvers += "Artima Maven Repository" at "http://repo.artima.com/releases"
``` 

Please update the readme so that no other poor souls fall prey to the same issue I did.

**Comment by OOPMan** [comment]
@roansong That's odd, it seemed to work fine adding it to the project sbt stuff. Will double-check, maybe I accidentally had that resolver already...

**Comment by OOPMan** [comment]
Weird, this doesn't affect me at all
